// This file is generated by scripts/generate-stories-index.mjs
// It imports each story so they register themselves on window.__FABLR_STORIES__
import './fablr-button.stories.js';
import './fablr-input.stories.js';
import './fablr-card.stories.js';

export const storiesRegistry = window.__FABLR_STORIES__ || [];